### ISSUE TITLE
Allow pinning Bandit version as an action input parameter?

### ISSUE THREAD

**Issue by leofang** [PyCQA/bandit-action#13]
**Is your feature request related to a problem? Please describe.**
Currently we let `pip install` float:
https://github.com/PyCQA/bandit-action/blob/b44244a5ce8d5c4963550acfc922273f6a89e97f/action.yml#L80
However, we'd like to have a precise control over the `bandit` version in use for security purposes.

**Describe the solution you'd like**
Allow it to be set as an action input:
```yaml
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1
        with:
          version: 1.8.3
```

**Describe alternatives you've considered**
n/a

**Additional context**
n/a
